// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;

namespace SunflowSharp.Systems
{
	public class FileUtils {
		/**
* Extract the file extension from the specified filename.
*
* @param filename filename to get the extension of
* @return a string representing the file extension, or <code>null</code>
* if the filename doesn't have any extension, or is not a file
*/
		public static string getExtension(string filename) {
			if (filename == null)
				return null;
			string extension = Path.GetExtension(filename);
			if (extension != null) 
				return extension.Substring(1);
			return null;
		}
	}
}

