// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SunflowSharp.Image.Formats
{
	public class BitmapG8 : Bitmap {
		private int w, h;
		private byte[] data;
		
		public BitmapG8(int w, int h, byte[] data) {
			this.w = w;
			this.h = h;
			this.data = data;
		}
		
		public override int getWidth() {
			return w;
		}
		
		public override int getHeight() {
			return h;
		}
		
		public override Color readColor(int x, int y) {
			return new Color((data[x + y * w] & 0xFF) * INV255);
		}
		
		public override float readAlpha(int x, int y) {
			return 1;
		}
	}
}

