// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace SunflowSharp.Image.Formats
{
	public class BitmapBlack : Bitmap {
		public override int getWidth() {
			return 1;
		}
		
		public override int getHeight() {
			return 1;
		}
		
		public override Color readColor(int x, int y) {
			return Color.BLACK;
		}
		
		public override float readAlpha(int x, int y) {
			return 0;
		}
	}
}

