// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SunflowSharp.Image
{
	public abstract class Bitmap {

		public static float INV255 = 1.0f / 255;
		public static float INV65535 = 1.0f / 65535;
		
		public abstract int getWidth();
		
		public abstract int getHeight();
		
		public abstract Color readColor(int x, int y);
		
		public abstract float readAlpha(int x, int y);
	}
}

