// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace SunflowSharp.Image
{
	public abstract class BitmapReader 
	{
		/**
		 * Load the specified filename. This method should throw exception if it
		 * encounters any errors. If the file is valid but its contents are not
		 * (invalid header for example), a {@link BitmapFormatException} may be
		 * thrown. It is an error for this method to return <code>null</code>.
		 *
		 * @param filename image filename to load
		 * @return a new {@link Bitmap} object
		 * @param isLinear if this is <code>true</code>, the bitmap is assumed to
		 *            be already in linear space. This can be usefull when reading
		 *            greyscale images for bump mapping for example. HDR formats can
	     *            ignore this flag since they usually always store data in
	     *            linear form.
		 */
		public abstract Bitmap load(string filename, bool isLinear);
		
		/**
		 * This exception can be used internally by bitmap readers to signal they
		 * have encountered a valid file but which contains invalid content.
		 */
		public class BitmapFormatException : Exception {
			public BitmapFormatException(String message) : base (message) { return ;}
		}
	}
}

